### ISSUE TITLE
definition of $clpcreate

### ISSUE THREAD

**Issue by mkazuyuki** [EXPRESSCLUSTER/CreateClusterOnLinux#1]
CommandParameters_jp.md に記載されているスクリプトについて
- $clpcreate が定義されていないようです。
- perl スクリプトのように見えますが、shebang を書くか 言語を明示するとよいと思います。

**Comment by oga-clp** [comment]
ご指摘ありがとうございます。
ドキュメントの可読性向上のため、サンプルスクリプト自体をドキュメント中には記載しない方針とすることに決めました。
サンプルスクリプトは、"template_scripts"フォルダにアップロード済です。
